[package]
name = "hodgkin_huxley_model"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "hodgkin_huxley_model"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
