[package]
name = "alphasynapse_model"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "alphasynapse_model"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
